### ISSUE TITLE
Renaming an asset fails to update database

### ISSUE THREAD

**Issue by joshuabaker** [craftcms/aws-s3#108] opened 2021-02-10 17:30 UTC
### Description

When renaming an asset the file is renamed on S3, however, the filename is not changed in the database, which causes broken links.

### Additional info

- Craft version: 3.5.17.1
- PHP version: 7.4.4
- Database driver & version: MySQL 5.7.26
- Plugin version: 1.2.11

**Comment by joshuabaker** [comment] 2021-02-10 17:37
nystudio107/craft-imageoptimize#253

**Comment by andris-sevcenko** [comment] 2021-02-11 10:47
Can you elaborate what you mean with "renaming an asset"?  Do you mean with the action shown in the screenshot?

If that is the case, then I'm unable to reproduce this with the exact versions of the CMS and plugin, so I would have to guess something else is at play here.

<img width="232" alt="Screen Shot 2021-02-11 at 12 46 35" src="https://user-images.githubusercontent.com/1891118/107626937-30238e80-6c67-11eb-8e5a-b5001df8070d.png">

**Comment by joshuabaker** [comment] 2021-02-11 10:52
> Can you elaborate what you mean with "renaming an asset"? Do you mean with the action shown in the screenshot?

Anywhere an asset can be renamed; The ‘Assets’ section (as per your screenshot), the asset edit view or via another element edit view.

---

I think the issue might be related to image transforms via the ImageOptimize plugin (nystudio107/craft-imageoptimize#255).

**Comment by andris-sevcenko** [comment] 2021-02-11 11:35
I'll go ahead and close this, as this does not appear to be caused by the plugin or Craft itself.

**Closed** 2021-02-22 08:37 UTC
Labels: bug
