### ISSUE TITLE
Default Upload Location Not Working

### ISSUE THREAD

**Issue by tinchco** [craftcms/aws-s3#4] opened 2017-04-30 02:21 UTC
Used the {id} variable to place the uploaded assets into a folder titled with the entry ID, but it still uploads to the root of the parent folder.

**Comment by andris-sevcenko** [comment] 2017-05-01 16:58
Default upload location is used only in instances when a file is dragged onto the field (https://craftcms.com/docs/assets-fields). Is that what you're doing? Because I'm having trouble reproducing this locally.

**Comment by brandonkelly** [comment] 2017-05-02 00:00
@tinchco Is the “Restrict uploads to a single folder?” setting checked in your Assets field? If not, the default upload location will only take effect when drag/dropping a file directly onto the field, without pressing the “Add an asset” button.

**Comment by tinchco** [comment] 2017-05-02 02:57
Ah, that did the trick. Kind of strange that uploading via drag/drop puts it into a folder while using "Add an asset" does not. Was there a particular use case you were trying to address by having different functionality occur depending on how a user interacts with the field?

**Comment by brandonkelly** [comment] 2017-05-02 13:39
Because when you are uploading an asset via the modal, you already have a folder selected in the sidebar, so you’re already telling Craft exactly where the file should live.

**Closed** 2017-06-20 18:40 UTC
