### ISSUE TITLE
Image transforms not working after migration to Craft 3

### ISSUE THREAD

**Issue by emandiev** [craftcms/aws-s3#102] opened 2020-10-15 08:25 UTC
### Description

Hello fellow crafters!

I'm facing an issue with an Amazon S3 volume.

I upgraded a Craft 2 installation to Craft 3.
The exact versions are 2.9.2 and 3.5.12.1
After the update, I got a prompt to install the Amazon S3 plugin and I did.
The existing Amazon S3 volume's settings were migrated automatically.
From this moment on, I cannot get image transforms.
I also don't see image thumbnails in the control panel.
However, I can get the full-size images and they render correctly.

The exact error I get is:
```
POST https://sts.s3.amazonaws.com` resulted in a `412 Precondition Failed` <Error><Code>PreconditionFailed</Code><Message>At least one of the pre-conditions you specified did not hold</Message><Condition>Bucket POST must be of the enclosure-type multipart/form-data</Condition><RequestId>CAA883CBB619CE09</RequestId><HostId>mhen/QNQVMbdw79Q2lbejRzY+ESIPrNTabDepI3nknxPQnf1DH0Ox3bNxWfsPGdjosdDSM9VLms=</HostId></Error>
```

I guess that the issue boils down to "Bucket POST must be of the enclosure-type multipart/form-data".
I tried following the AWS client and Guzzle request logic in the code, but weren't able to fix it.

The current volume settings are:
Base URL: https://s3.amazonaws.com/lexingtonvirginia.com/
Bucket: Manual | lexingtonvirginia.com | s3
Make Uploads Public: true

I tried different volume settings, regions, base URLs, etc. but nothing helps.

I've used the Amazon S3 storage solution for several Craft 3 projects in the past and never faced this issue.
The only difference I see with this project is the fact that the Amazon endpoint doesn't use regional codes.
For example, if I add "us-west-1" to the endpoint, I get a message to use the "plain" version.
https://s3.us-west-1.amazonaws.com/lexingtonvirginia.com/
So I guess that this is the correct one: https://s3.amazonaws.com/lexingtonvirginia.com/

Again, all full-sized images are working correctly, so the endpoint should be good.

Any suggestions are greatly appreaciated.

Thanks!

### Steps to reproduce
1. Have a Craft 2.9.2 install with an Amazon S3 volume
2. Migrate to Craft 3.5 https://craftcms.com/docs/3.x/upgrade.html
3. Install this plugin https://plugins.craftcms.com/aws-s3
4. Image transforms don't work (error 412)

### Additional info
- Craft version: 3.5.12.1
- PHP version: 7.3.16
- Database driver & version: MySQL 5.7.25
- Plugins & versions: Amazon S3 1.2.11

I tried running the website on another environment and got the same result.

**Comment by andris-sevcenko** [comment] 2020-10-21 08:14
Resolved over support, ended up being a duplicate of #36

**Closed by andris-sevcenko** 2020-10-21 08:14 UTC
Labels: bug
