### ISSUE TITLE
Replaced image (same filename) transforms are not cleared

### ISSUE THREAD

**Issue by Tim-Wils** [craftcms/aws-s3#62] opened 2019-07-23 08:09 UTC
Hey guys!
We ran into a bug where our image-transforms are not cleared when a asset was replaced with the same filename.

We got visual3.png and replaced it with another image with the same filename. The base file is uploaded to Amazon, but the transforms aren't cleared at the S3 side, so the templates wil keep the old transforms.

Even after Asset-reindexing and cache-clear S3 seems to keep them.

Specs:

PHP version | 7.1.25
Linux 4.9.125-linuxkit
MySQL 5.7.24
Imagick 3.4.3 (ImageMagick 6.9.7-4)
Craft Solo 3.2.4.1
2.0.21
2.11.3
6.3.3
0.7-dev

**Comment by andris-sevcenko** [comment] 2019-07-23 08:22
Any chance you have Cloud Front set up as well?

**Comment by divyan** [comment] 2019-07-23 12:27
No I only use the bucket (without CloudFront) for now :)

**Comment by andris-sevcenko** [comment] 2020-05-18 07:21
I'm unable to reproduce this, so closing this for now.

Are you still encountering this? How are you replacing the file?

**Closed by andris-sevcenko** 2020-05-18 07:21 UTC
