### ISSUE TITLE
Attempting to download an asset returns `fseek(): stream does not support seeking` PHP error

### ISSUE THREAD

**Issue by aaronbushnell** [craftcms/aws-s3#100] opened 2020-09-24 16:42 UTC
### Description
I recently upgraded a client from Craft 2.x to 3.x and connected their S3 volumes using the S3 plugin. However, when I try to download an asset from the control panel I receive this error:

```
fseek(): stream does not support seeking
```

I'm not entirely sure why though. Is a download trying to use `file_get_contents()` but, because it's a remote file, it fails? If so, is there something not properly set up in our asset volume? Or is this an AWS permission issue? 

### Additional info

- Craft version: 3.4.29
- PHP version: 7.1.33
- Database driver & version: MySQL 5.6.10
- Plugins & versions: Amazon S3 `1.2.10`

**Comment by aaronbushnell** [comment] 2020-09-24 16:45
Here's a screengrab of the error! 
![Screen Shot 2020-09-23 at 4 17 10 PM](https://user-images.githubusercontent.com/315202/94174802-c0516a80-fe63-11ea-9591-4eda40005d68.png)

**Comment by andris-sevcenko** [comment] 2020-09-24 17:09
Thanks for reporting!

However, this is a duplicate of #95 and resolved by updating to the latest version of the plugin!

**Closed by andris-sevcenko** 2020-09-24 17:09 UTC
Labels: bug

**Comment by aaronbushnell** [comment] 2020-09-24 17:16
Oh sheesh, thanks so much @andris-sevcenko! We'll update! 😊
